x-common-volumes: &common-volumes
  - ./:/MoneyPrinterTurbo

services:
  webui:
    build:
      context: ./webui-react
      dockerfile: Dockerfile
    container_name: "moneyprinterturbo-webui"
    ports:
      - "8001:80"
    depends_on:
      - api
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "moneyprinterturbo-api"
    ports:
      - "8081:8081"
    command: [ "python3", "main.py" ]
    volumes: *common-volumes
    restart: always
